### PR TITLE
Remove uncessary precondition checks

### PR DESCRIPTION
**Pull request by danielcweeks**
These checks unnecessarily prevent checking how much data has been written.

### CODE REVIEW

**Comment by rdblue** [comment]
I think this also needs to update the `length` javadoc because the requirement that the appender has been closed is no longer needed.

**Comment by danielcweeks** [comment]
> I think this also needs to update the `length` javadoc because the requirement that the appender has been closed is no longer needed.

Good spot.  I've updated the javadoc.

**Comment by rdblue** [comment]
Here's the problem:

```
[ant:checkstyle] [ERROR] /home/travis/build/apache/incubator-iceberg/core/src/main/java/org/apache/iceberg/avro/AvroFileAppender.java:22:8: Unused import - com.google.common.base.Preconditions. [UnusedImports]
```

**Comment by aokolnychyi** [comment]
@danielcweeks @rdblue shall we update `ReplaceManifests` to use `length` instead of estimating the size of each entry?

**Comment by danielcweeks** [comment]
@aokolnychyi Excellent observation! Yes, we should switch the estimate over to use the length (@bryanck, FYI)

**Comment by bryanck** [comment]
Nice! I'll create a PR for this.

**Pull request merged**
