### PR TITLE
Updating travis to use bionic

### PR DESCRIPTION
**Pull request by TGooch44**
Updating travis to use bionic instead of trusty. @chyzzqo2 do you think I should be updating this to use python 3.7 too?

cc: @rdblue @danielcweeks

### CODE REVIEW

**Comment by chyzzqo2** [comment]
python 3.6 is still pretty widely used so i think it's find to leave it there as the baseline. Unless of course you actually want / need 3.7 only features.

**Comment by Fokko** [comment]
I would support from 3.6 and higher. At this moment, it is only from 3.4 and onwards: https://github.com/apache/incubator-iceberg/blob/master/python/setup.py#L28

**Comment by Fokko** [comment]
Related: https://github.com/apache/incubator-iceberg/pull/795

**Comment by rdblue** [comment]
Looks like the Java test failure is caused by a new Java default version that isn't Java 8. Can we pin to Java 8 in the matrix?

**Pull request merged**
