### PR TITLE
Make the static factory methods of the MappedField and MappedFields c…

### PR DESCRIPTION
**Pull request by puneetzaroo**
…lasses public.

Make the static factory methods of the MappedField and MappedFields classes public,
so that other classes can also invoke them.

### CODE REVIEW

**Comment by rdsr** [comment]
Hi @puneetzaroo  could you comment here on why is this change required?

**Comment by puneetzaroo** [comment]
> Hi @puneetzaroo could you comment here on why is this change required?

In order to be able generate a mapping the static constructor needs to be accessible to the utility that is generating the mapping.
thanks,

**Comment by rdsr** [comment]
Is this some utility that you are writing?  
I used `org.apache.iceberg.mapping.MappingUtil#create` which is under the same package name and is able to access MappedFields to correctly create the `NameMapping`

**Comment by puneetzaroo** [comment]
Yes, this is a utility I am writing. And yes, I do not want to  create the mapping from a table schema; as the mapping is not completely derivable from the schema itself, but is has to be carried over from a different (legacy) system.

**Comment by rdblue** [comment]
+1

Thanks for adding this, @puneetzaroo!

**Pull request merged**
