### PR TITLE
Issue-1065: Unable to read Iceberg table with hadoop spark options

### PR DESCRIPTION
**Pull request by mehtaashish23**
Copies method `mergeIcebergHadoopConfs` from IcebergSource and used it to extract Hadoop config sent as options.

### CODE REVIEW

**Comment by rdblue** [comment]
Can you describe the problem with a bit more detail? Where are you passing options and why are they not carried through?

**Comment by mehtaashish23** [comment]
@rdblue : We use spark options to send hadoop configurations (specifically mentioned below), to read/write to Iceberg table. These options have helped in reading/writing when we have multiple SparkSession (which shares hadoop configuration on Global spark Context), each belonging to a tenant, and each tenant can potentially have different creds (have different ACLs as well).

There is multi tenant configuration also available like `dfs.adls.oauth2.client.id.{accountName}`, which can be set on sparkContext, but we don't want to expose the creds from one session to other. Make sense? I think it will help in scenarios, even multi tenant hadoop configuration aren't supported by underlying store.

NOTE: This is already supported [here].


```
hadoop.dfs.adls.oauth2.client.id={clientId}
```

[here]: https://github.com/apache/incubator-iceberg/blob/master/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java#L180

**Comment by mehtaashish23** [comment]
I think I am missing on merging the properties from table. Let me do that, that's being done in IcebergSource.

**Comment by rdblue** [comment]
Okay, so it sounds like the FileIO for the table is created correctly, it is just the locality code that is a problem?

**Comment by mehtaashish23** [comment]
@rdblue : Yes its just the locality code, which is missing on this, IcebergSource is already doing this, as mentioned. The exception we see is inside DataBricks. 

I will piggy back this stacktrace on Issue as well. 
```
stacktrace: java.lang.IllegalArgumentException: No value for fs.adl.oauth2.access.token.provider found in conf file. 
at com.databricks.adl.AdlFileSystem.getNonEmptyVal(AdlFileSystem.java:804) 
at com.databricks.adl.AdlFileSystem.getCustomAccessTokenProvider(AdlFileSystem.java:204) 
at com.databricks.adl.AdlFileSystem.getAccessTokenProvider(AdlFileSystem.java:241) 
at com.databricks.adl.AdlFileSystem.initialize(AdlFileSystem.java:148) 
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669) 
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370) 
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) 
at org.apache.iceberg.spark.source.Reader.<init>(Reader.java:128) 
at org.apache.iceberg.spark.source.IcebergSource.createReader(IcebergSource.java:126) 
at org.apache.iceberg.spark.source.IcebergSource.createReader(IcebergSource.java:89) 
at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155) 
at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172) 
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286) 
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214) 
```

**Comment by rdblue** [comment]
Alright, this proposed fix seems reasonable to me, then.

**Comment by rdblue** [comment]
Thanks, @mehtaashish23! Merged.

**Comment by mehtaashish23** [comment]
Thanks Ryan, appreciate the prompt merge. This has actually unblocked our use case within a day!

**Pull request merged**
