### PR TITLE
Add finalizer for Hadoop streams to catch paths that don't call close.

### PR DESCRIPTION
**Pull request by rdblue**
This adds a finalizer that closes open streams when they are garbage collected. It also logs the stack that opened the stream to catch leaks.

### CODE REVIEW

**Comment by fbocse** [comment]
Afaik `Object.finalize()` isn't the best option out there for resource reclaiming, unless it's the only option, is it in this particular case?
I mean, would it work if we were to be looking into more naive alternatives such as having `HadoopSeekableInputStream` and `HadoopPositionOutputStream` both implement (which they already do) `java.lang.AutoCloseable` and just rely on always using `try-with-resources` when working with `com.netflix.iceberg.io.SeekableInputStream` instances from `com.netflix.iceberg.hadoop.HadoopStreams#wrap(org.apache.hadoop.fs.FSDataInputStream)`?

Afaik object finalization is complicated because it's basically nondeterministic, it depends on GC firing (that's basically a bunch of heuristics, might as well roll a dice), no guarantees to be called before program exits, no guarantees on the ordering in which JVM will invoke the objects' finalizer methods, all finalizers are treated "fairly" so objects holding on to considerable resources are queued up waiting for objects whose finalizers are slowly progressing, etc.  of and also seeing as `Object.finalize()` has become deprecated with [Java 9](https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#finalize--)

**Comment by rdblue** [comment]
@fbocse, this is not the intended way to clean up resources. This is a way to handle leaks so that you get nice warning messages instead of failing applications when a resource pool runs out.

Iceberg already uses try-with-resources and is careful about cleaning up open files internally, but it also returns open streams to callers as `CloseableIterable` instances. If callers leave those open, a finalizer is better than doing nothing.

**Comment by danielcweeks** [comment]
+1 LGTM

**Comment by aokolnychyi** [comment]
Has anybody experienced the exception below? One way to reproduce this is to run `TestParquetWrite`.

```
[Finalizer] WARN com.netflix.iceberg.hadoop.HadoopStreams - Unclosed input stream created by:
	com.netflix.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.<init>(HadoopStreams.java:78)
	com.netflix.iceberg.hadoop.HadoopStreams.wrap(HadoopStreams.java:53)
	com.netflix.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:125)
	com.netflix.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:95)
	com.netflix.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)
	com.google.common.collect.Iterables$6.iterator(Iterables.java:585)
	com.google.common.collect.Iterables$8.iterator(Iterables.java:709)
	com.netflix.iceberg.ManifestReader.iterator(ManifestReader.java:225)
	com.netflix.iceberg.FilteredManifest.iterator(FilteredManifest.java:124)
	com.google.common.collect.Iterables$8.iterator(Iterables.java:709)
	com.google.common.collect.Iterables$3.transform(Iterables.java:508)
	com.google.common.collect.Iterables$3.transform(Iterables.java:505)
	com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	com.netflix.iceberg.util.BinPacking$PackingIterator.hasNext(BinPacking.java:91)
	com.netflix.iceberg.io.CloseableIterable$4$1.hasNext(CloseableIterable.java:92)
	com.google.common.collect.Iterators.addAll(Iterators.java:356)
	com.google.common.collect.Lists.newArrayList(Lists.java:147)
	com.google.common.collect.Lists.newArrayList(Lists.java:129)
	com.netflix.iceberg.spark.source.Reader.tasks(Reader.java:209)
	com.netflix.iceberg.spark.source.Reader.planInputPartitions(Reader.java:135)
	org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.partitions$lzycompute(DataSourceV2ScanExec.scala:76)
...
```

It seems `ManifestReader` is not closed properly in some cases. `ManifestReader` is `CloseableGroup` and we add `AvroIterable` to the list of closeables. However, `ManifestReader$close` is not called.

**Comment by aokolnychyi** [comment]
My suspicion is that we have a problem in `BaseTableScan$planFiles`. Specifically, this piece:

```
      ConcurrentLinkedQueue<Closeable> toClose = new ConcurrentLinkedQueue<>();
      Iterable<Iterable<FileScanTask>> readers = Iterables.transform(
          matchingManifests,
          manifest -> {
            ManifestReader reader = ManifestReader.read(ops.io().newInputFile(manifest.path()));
            toClose.add(reader);
            String schemaString = SchemaParser.toJson(reader.spec().schema());
            String specString = PartitionSpecParser.toJson(reader.spec());
            ResidualEvaluator residuals = new ResidualEvaluator(reader.spec(), rowFilter);
            return Iterables.transform(
                reader.filterRows(rowFilter).select(SNAPSHOT_COLUMNS),
                file -> new BaseFileScanTask(file, schemaString, specString, residuals)
            );
          });

      if (PLAN_SCANS_WITH_WORKER_POOL && snapshot.manifests().size() > 1) {
        return CloseableIterable.combine(
            new ParallelIterable<>(readers, getWorkerPool()),
            toClose);
      } else {
        return CloseableIterable.combine(Iterables.concat(readers), toClose);
      }
```

The closure that adds `ManifestReader reader` to `toClose` is lazy. Hence, `toClose` is empty when we return `CloseableIterable.combine(Iterables.concat(readers), toClose)`.

**Comment by rdblue** [comment]
@aokolnychyi, those code paths are what this is intended to catch. Could you open an issue or PR for this one?

**Comment by aokolnychyi** [comment]
Let's tack it in https://github.com/apache/incubator-iceberg/issues/104.

**Pull request merged**
