### PR TITLE
Refactor AvroIterable and prevent multiple iterators

### PR DESCRIPTION
**Pull request by vrozov**

### CODE REVIEW

**Comment by rdblue** [comment]
@vrozov, can you give more context for why you'd like to make this change? It is strange to make an `Iterable` produce only one iterator and I don't think there is a compelling reason to do this.

**Comment by vrozov** [comment]
The change helps to avoid resource shortage: as it is `AvroIterable` that is `Closeable`, not the `Iterator`, resources acquired in the `iterator()` won't be closed until `AvroIterable` itself is closed and in the case where multiple iterators are obtained from the same `AvroIterable`, there will be multiple file handles/sockets/http connections acquired and pointing to the same file/bucket that can't be closed individually.

Note that `org.apache.avro.file.DataFileReader` follows a similar pattern. It is not possible to get multiple iterators from `DataFileReader` as it always returns the same iterator instance (itself).

@rdblue What will be a use case were support for multiple iterators is necessary and that can't be covered by creating multiple `AvroIterable` instead?

**Comment by rdblue** [comment]
@vrozov, all of the iterators are closeable, so we should be able to close them as they are consumed to free up resources. We do this in `ParallelIterable` for example.

The close method in `CloseableIterable` is really intended to be a second catch-all to avoid eventual leaks. Plus, it allows using try-with-resources:

```java
try (AvroIterable records = Avro.read(...).build()) {
  for (R record : records) {
    ...
  }
}
```

**Comment by vrozov** [comment]
@rdblue While iterators returned by `AvroIterable.iterator()` are `Closeable`, they are unlikely to be closed. In your example, it is `AvroIterable.close()` that closes `Iterator` that java implicitly obtains from `records` and there is no implicit or explicit call to the iterator `close()` method. In `ParallelIterable` it is Iterable that is closed (assuming that you refer to https://github.com/vrozov/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/ParallelIterable.java#L63) not the iterator.

The PR prevents constructs like
```
try (AvroIterable records = Avro.read(...).build()) {
  for (R record : records) {
    ...
  }
  
  for (R record : records) { // <-not allowed
    ...
  }
}
```

**Comment by rdblue** [comment]
@vrozov, I see what this PR does, but I don't think there is a good argument for making Iterables that can only be used once. Both iterables and iterators can be closed. If you'd prefer to close iterators earlier, then I think the right thing to do is to update code to do that, instead of disallowing reasonable uses.

**Comment by vrozov** [comment]
@rdblue What is the use case where `AvroIterable` needs to be used more than once? At minimum, there is no such use case in the current code base as the PR does not break existing functionality. Code to close iterators earlier will be extremely verbose and I would prefer not to do that.

**Comment by rdblue** [comment]
The expectation is that iterables can be used more than once. Breaking that expectation should be worth the trade-off and I don't see a reason to change it. All of these can be closed. If you want an iterator closed earlier, then we can close it earlier.

**Comment by vrozov** [comment]
There is no such assumption in `org.apache.avro.file.DataFileReader` and there is no such expectation in the existing iceberg code. Ability to get multiple iterators from `AvroIterable` will promote code that leads to performance degradation: `AvroIterable` iterator does file I/O, iterating twice like in the code example I provided, should be discouraged in favor of a single iteration over avro file.

**Comment by vrozov** [comment]
@rdblue Does the above provide sufficient justification not to support multiple iterators? If not, can you please provide a use case where such support is necessary so that I can take it into account and modify the code accordingly?

**Comment by rdblue** [comment]
@vrozov, no. There is no way for Iterable to signal that it only supports a single iteration, and most iterables, like lists, maps, sets, etc. support iteration multiple times. I think that there isn't much point to using Iterable if you only intend to support a single iteration.

The goal you want to accomplish should be done by making sure that resources are closed. I think a better approach would be for an iterator to close underlying resources automatically when it is exhausted.

**Comment by vrozov** [comment]
@rdblue Please take a look at `DataFileReader`. It supports only one iterator. `AvroIterable` also supports only one iterator and it provides the signal (`IllegalStateException`) should somebody try to obtain a second iterator.

There is a difference between iterating over in-memory collection and iterating over records in file: list, map, set iterators do not need to be closed and there is no significant cost associated with the second iteration over in-memory collection.

The point of using Iterable even with a single iterator() is 
1. support "for-each loop"
2. ability to pass Iterable and delay creating Iterator instance.

I considered the approach to close an iterator when `hasNext()` returns `false`, but rejected it as it is not necessary to exhaust iteration (even though most of the time iterator will be fully exhausted), so the resource may be left open.

The PR does not fix any existing resource leakage or shortage. The goal of the PR is to prevent such a possibility for future modifications.

**Comment by rdblue** [comment]
I get the argument, and I know that Avro has a class that does something else. I'm saying that Iceberg should not violate a common assumption about iterables without a good reason. I don't think your justification for this is sufficient. If you want to clean up resources more quickly, then the right way to do that is in the iterators returned by these iterables.

**Comment by vrozov** [comment]
iceberg already violated the common assumption about iterator in two ways
1. `Iterator` returned by the `iterator()` is "usually" (personally I don't know any) not `Closeable` as the primary use case for the `iterator()` method is "for-each loop", so making `Iterator` `Closeable` is not well justified as `close()` is not called in "for-each loop".
1. `AvroReuseIterator` always returns the same reference in the `next()` method. This is a much bigger "violation" of a common `Iterator` behavior.

I do not say that I see a problem with those "violations" and I see why those approaches were taken, but I don't see why it is a problem to introduce `Iterable` that allows only single `iterator()` in favor of less error-prone code and that does not break any existing assumptions in iceberg.

**Comment by rdblue** [comment]
@vrozov: there are better ways to solve the problem. Closing resources in iterators is the right solution to this.

**Comment by vrozov** [comment]
@rdblue It is not a better way to solve the problem and I already explained why it does not work for "for each loop". All I see is multiple excuses to reject a contribution that goes from violating common assumptions (while other violations are somehow acceptable) to a "better way" that leads to resource leak or more error-prone code.

**Comment by rdblue** [comment]
To be clear, the problem is that this violates common assumptions that people make about iterables. In Iceberg, we make sure that iterables can be used multiple times and, although we don't use this internally, these are part of the guarantees in the public API.

I also disagree with the justification for making this change. Preventing resource leaks is not a valid justification because there are better ways to handle it, like closing when an iterator has been consumed.

I'm sorry to hear that this sounds like multiple excuses to you, but I think my position has been consistent. This would make iterables have surprising behavior, which is bad, and doesn't have a strong enough justification for that surprising behavior because I don't think it would be more effective than other changes.

**Comment by vrozov** [comment]
It goes in a circle. I already explained that people make other assumptions about Iterables and Iterators, but somehow it is OK to violate those assumptions and not OK to violate another assumption. Would you agree that iterating twice over the same file should be discouraged in favor of single iteration and when necessary it is possible to get Iterable without any extra performance penalty? In rear cases where multiple iterators are necessary, it is easy to go from 
```
try (AvroIterable records = Avro.read(...).build()) {
  for (R record : records) {
    ...
  }
  
  for (R record : records) {
    ...
  }
}
```
to
```
try (AvroIterable records = Avro.read(...).build()) {
  for (R record : records) {
    ...
  }
}
...  
try (AvroIterable records = Avro.read(...).build()) {
  for (R record : records) {
    ...
  }
}
```
There is also no better way. Iterators are not expected to be `Closeable` and it is very easy to lose `Closeable` iterator during Iterable transformation. For example `CloseableIterable.transform()` does not preserve `Closeable` and guava `Iterables` won't preserve it either.

The only consistency I see in this PR review is the denial of the contribution. Arguments provided changed from "not a common violation" to "there is a better way". When I asked for a "use case" it was never provided.

In any case, the PR is closed and there is no need to discuss this further. I am working away from contribution to the iceberg project.

**Comment by rdblue** [comment]
I think you misunderstand my suggestion. What I see as a better solution is removing the need to explicitly close Iterator if the iterator exhausts its contents. That would alleviate the need to call close on the iterator in most cases.

> I already explained that people make other assumptions about Iterables and Iterators, but somehow it is OK to violate those assumptions and not OK to violate another assumption

Your examples were `Iterator` not typically implementing `Closeable`, and reusing objects in `AvroReuseIterator`:

* It is true that `Iterator` typically doesn't implement `Closeable` and it is hard to keep track of when using `for` loops. That's why `CloseableIterable` can be used in a try-with-resources block. I'm also suggesting that iterators should close underlying resources when finished iterating, which would solve this problem earlier if iterator is completely consumed.
* `AvroReuseIterator` is not used by default. Callers must use `reuseContainers` on the read builder, which I think is a reasonable compromise. The performance benefit and the steps we've taken to guard against accidental use justifies this change.

> Would you agree that iterating twice over the same file should be discouraged in favor of single iteration and when necessary it is possible to get Iterable without any extra performance penalty?

I agree that what you're suggesting would work. But it would be surprising behavior. Callers would not know until runtime that they should have used the second of your two code blocks instead of the first. The choice here is to avoid throwing exceptions at runtime when we can leave resources around for a bit longer and avoid a failure.

**Comment by vrozov** [comment]
@rdblue Closing resource in an iterator when it (iterator is exhausted) is not a "better" solution, it is the mitigation for the resource leak/shortage issue. Otherwise, it would not be necessary for `AvroIterable` to be `CloseableIterable`. Such a solution still leaves a possibility for the resource shortage. It will also require a wrapper around `DataFileReader` as `DataFileReader` iterator does not close the underlying resource when it is exhausted. So, all `CloseableIterable` still needs to be closed either explicitly or by using a try-with-resources block. Note that a common expectation for `Closeable` or `AutoCloseable` used in a try-with-resources block is that there is a single resource acquired and that is guaranteed to be closed, not multiple resources as in the case of `CloseableGroup`. Additionally `CloseableGroup' is a subject of resource leak: should `close()` for one of `Closeable` in `closeables` throw an `IOException` or `RuntimeException`, all other `Closeable` won't be closed.

It sounds that the major disagreement is whether it is OK to keep resources a little bit longer and allow multiple iterators or it is better to ensure that a resource is released asap but fail multiple iterators request. After spending a significant effort in isolating iceberg resource leak/shortage in our environment, my strong preference and recommendation is to fail fast when resources are not released asap. In an environment where resources are limited, the first behavior will still lead to run-time errors.

**Comment by rdblue** [comment]
Would closing when an iterator is exhausted solve the resource leak you found? What caused the leak you found? Having more concrete information about your situation might help.

**Comment by vrozov** [comment]
It was the same leak as was fixed in #150. It is not a question of how to fix an existing leak. The PR goal is to prevent introducing such leaks in the future and helping with troubleshooting resource leak/shortage conditions.

**Comment by rdblue** [comment]
Okay, do you agree that closing the iterator when exhausted would help avoid such leaks in the future?

**Comment by vrozov** [comment]
It will mitigate such possibility, but will not eliminate it completely. For example, it won't work in case of 
``` java
try (AvroIterable records = Avro.read(...).build()) {
  for (R record1 : records) {
    for (R record2 : records) {
      ...
    }
  }
```

**Comment by rdblue** [comment]
I think in the first case, closing the iterator would do the right thing. Each inner iterator would be closed before the next one is opened, and the outer iterator must be left open the entire time because it is still in use.

For the second case, I agree that the first iterator's resources are left open until the end of the try-with-resources, block. I think that's worth the trade-off, and callers can always close the iterator if they choose. So I'm okay with the trade-off of using the automatic close at the end of the try block.

**Comment by vrozov** [comment]
I already explained and, I believe, you already agreed that callers
1. won't be able to choose to close an iterator as `Closeable` may be easily lost
1. the code by itself does not imply that there are multiple resources acquired. When a person reads such code, she likely will assume that there is a single resource acquired in try-with-resources.

Both cases are examples where logic needs to be modified. For example instead of 
```java
try (AvroIterable records = Avro.read(...).build()) {
  for (R record : records) {
    ...
    break;
  }
  for (R record : records) {
    ...
  }
}
```
it should be written as
```java
List<Record> recordsCached = new ArrayList<>();
try (AvroIterable records = Avro.read(...).build()) {
  Iterators.addAll(recordsCached, records.iterator());
}

for (R record : recordsCached) {
  ...
  break;
}
for (R record : recordsCached) {
  ...
}
```
ability to get multiple iterators promotes less code in favor of less performant code. It should be explicit for callers that they are iterating over a file resource that needs to be closed and that iterating twice over a file is much slower compared to an in-memory collection. Making it implicit will lead to resource leaks and a significant effort in isolating such resource leaks. It is a trade-off for allowing only one active (note additional changes) iterator.

**Comment by rdblue** [comment]
> won't be able to choose to close an iterator as Closeable may be easily lost

If the caller cares about the case where a partially consumed iterator is left open until the end of the try block, then they can close it and use a while loop instead of the for loop. It is easy to do this, but most people won't care.

Your rewrite assumes that it is reasonable to keep records in memory. That's not necessarily the case.

**Comment by vrozov** [comment]
I see no point to discuss this further.

**Pull request closed without merging**
