### PR TITLE
Fix mkdocs and add missing footnotes

### PR DESCRIPTION
**Pull request by jun-he**

### CODE REVIEW

**Comment by rdblue** [comment]
Thanks for catching this, @jun-he! The footnotes plugin doesn't work well here because they are all added at the bottom of the spec in Appendix D. What about just moving the footnote text to the bottom of each section with "Note: "?

**Comment by jun-he** [comment]
@rdblue thanks for the comment! 
Yeah, this is a good idea and I have updated the PR accordingly.

**Comment by rdblue** [comment]
@jun-he, using `!!! note` blocks adds a large call-out that isn't suitable for footnotes, which should not draw attention. Also, footnote links do not work if you aren't using the footnote plugin and show up in the doc like this: "buckets[^1]".

I recommend running `mkdocs serve` to see how these changes look locally before updating the PR.

**Comment by jun-he** [comment]
@rdblue Got it. I updated the PR accordingly and moved footnotes into the `Notes`. I ran the mkdocs server and it looked OK. Please let me know if you have any comments. Thanks!

**Comment by rdblue** [comment]
Merged. Thanks @jun-he!

**Pull request merged**
