### PR TITLE
Remove iceberg-presto-runtime that is no longer used.

### LINKED ISSUE #160: [Baseline] Apply Baseline to iceberg-presto-runtime
Use the Baseline plugin to add linting for iceberg-presto-runtime. Part of the greater effort to apply Baseline across the project. (Issues are being created individually so that contributors can claim assignment for each of these).

### LINKED ISSUE #256: Cleanup Presto runtime artifact
Similar to #250, we need to remove usage and redefinition of `shadow configuration` in `presto-runtime` module. There's  probably some relocation/shading rules that also need to be added.

### PR DESCRIPTION
**Pull request by rdblue**
Fixes #256 and fixes #160.

### CODE REVIEW

**Comment by edgarRd** [comment]
I guess this fixes #160  too.

**Comment by vrozov** [comment]
What jar presto should include as a dependency?

**Comment by rdblue** [comment]
@vrozov, engines typically depend on `iceberg-core`, plus add-on modules like `iceberg-parquet` or `iceberg-orc`. It is unusual to have a dependency like this one, since the code for Presto integration is in Presto (instead of in Iceberg like `iceberg-spark`).

**Comment by vrozov** [comment]
I don't think that Presto will be able to use `iceberg-core` dependency directly due to the dependency on a different guava (and likely incompatible) version. It will also likely require `iceberg-hive` and won't be able to use it either due to the incompatible hive version. I guess either iceberg or presto (or any other project that adds iceberg support) will have to create 'runtime' uber/shade jar. In case it is done in iceberg, the same does not need to be repeated in any other projects that may be interested in supporting iceberg.

**Comment by rdsr** [comment]
@vrozov . Presto provides an SPI mechanism to load connectors. All jars that a connector needs are loaded in a separate classloader so there's complete classpath isolation between Presto and  its plugins (connectors) https://prestodb.github.io/docs/current/develop/spi-overview.html

**Comment by vrozov** [comment]
@rdsr I am aware of the Presto SPI mechanism for plugins. Problem is that it will not help as the issue is with the version conflicts within a plugin classloader, not across different plugins.

**Comment by rdblue** [comment]
@vrozov, Iceberg depends on an older version of Hive, but the calls we use are provided by newer versions. Hive provides backward compatibility on those calls. Projects like Presto can depend on Iceberg and use version management to update the version that is actually used.

Guava is similar. We want to depend on a new version, but only use calls that are compatible with most versions of Guava.

**Comment by vrozov** [comment]
@rdblue Unfortunately it is not the case and Hive does not provide backward compatibility (and is not required based on semver). The signature of `HiveMetaStoreClient` changed from `HiveConf` to `Configuration` in 3.x and there is no backward-compatible constructor that takes `HiveConf` in 3.x.

The same for guava. In the long run, it is not possible to provide a guarantee that nobody introduces the usage of an incompatible class or method. The only way to play safely is to shade guava due to it's wide acceptance and limited backward compatibility in early versions.

**Comment by rdblue** [comment]
@vrozov, good to know about the HiveMetaStoreClient constructor. We can update the constructor call to work in both 1.2.1 and 3.x variants. Sounds like the justification for Guava is that this could happen with that library as well. I agree with that, and we can either avoid calls that are problematic or use reflection for shims.

Either way, I'm not sure that it is necessary to create a shaded Presto runtime library. On #256, I asked whether Presto actually used this and the answer was no. If Presto needs one, we can add it back. Otherwise, I think we should publish normal dependencies and let Presto handle their transitive dependencies. If there is a problem, we are flexible and can work with that community to fix it.

**Comment by vrozov** [comment]
@rdblue Presto does not use iceberg libraries as Presto still does not support iceberg. There is an open PR to add such support and, I guess, the question is whether the PR uses `iceberg-presto-runtime` or `iceberg-api`, `iceberg-core` and other iceberg libraries directly. Indeed, the PR does not use `iceberg-presto-runtime` and my educated guess (that is based on adding iceberg support to presto  on a private fork where I did not use `iceberg-presto-runtime` either) is that this was done due to a wrong shading in `iceberg-presto-runtime` (there is a large number of classes that are included into `iceberg-presto-runtime` without being relocated, causing conflicts with presto own dependencies).

I still don't see anything in the PR that would solve `HiveMetaStoreClient` backward compatibility issue (note that there may be more incompatibilities in hive, just that it breaks on the very first call to hive), but I may be missing something. Possibly @electrum can clarify how hive version conflict is resolved in the PR.

Yes, while it is possible to resolve all such conflicts one by one after they are discovered (and likely they won't be discovered till it blows up during run-time) or it can be solved all in once by shading and creating uber run-time jar. Another option is to use something similar to `animal-sniffer-maven-plugin` to ensure API compatibility, but I don't know if gradle provides such ability.

**Comment by rdblue** [comment]
If you'd like to create a generic runtime Jar that shades and relocates dependencies, that would be great. It doesn't need to be specific to Presto, though.

**Comment by electrum** [comment]
@vrozov Presto does not use any of the metastore code from the Iceberg library. Instead, it uses its existing metastore code from the Hive connector which already has config that fits with Presto, handles Kerberos security, allows alternate metastore implementations such as Glue, etc. The same is true for other Iceberg code including file reading and writing.

**Comment by vrozov** [comment]
@electrum Problem is not whether presto uses the hive metastore code from the iceberg. Problem is that iceberg uses the hive metastore 1.x API and it is not compatible with hive 3.x API that presto provides at runtime.

**Comment by electrum** [comment]
@vrozov It doesn’t matter because Presto doesn’t use that code. The classes aren’t referenced at runtime.

BTW, just to clarify, the Presto engine doesn’t provide anything metastore or Hive related at runtime. The Iceberg plugin (like all plugins) is loaded in an isolated class loader and has complete control over all of its dependencies and versions. It is choosing to reuse code and dependencies from the Hive plugin.

**Comment by vrozov** [comment]
@electrum What classes are not referenced at runtime? Iceberg `org.apache.iceberg.hive.HiveClientPool` has compile time dependency on  `org.apache.hadoop.hive.metastore.HiveMetaStoreClient` and at run-time it is provided by `io.prestosql.hive:hive-apache`. What do I miss here?

> BTW, just to clarify, the Presto engine doesn’t provide anything metastore or Hive related at runtime. The Iceberg plugin (like all plugins) is loaded in an isolated class loader and has complete control over all of its dependencies and versions. It is choosing to reuse code and dependencies from the Hive plugin.
>> I am aware of the Presto SPI mechanism for plugins. Problem is that it will not help as the issue is with the version conflicts within a plugin classloader, not across different plugins.

**Comment by electrum** [comment]
`HiveClientPool` and related are not used in Presto. You can see the code: https://github.com/prestosql/presto/pull/1067

**Comment by rdblue** [comment]
> [Presto] uses its existing metastore code from the Hive connector which already has config that fits with Presto, handles Kerberos security, allows alternate metastore implementations such as Glue, etc.

@electrum, how did you add Glue support for Iceberg? Is that something that we should support in this repository so that Spark can read/write tables tracked in Glue? It would be great to be able to reuse what you guys already have done here.

**Comment by electrum** [comment]
@rdblue The Presto way is likely too complex for the Iceberg library, especially given that it only uses a few metastore calls, but I can share how it works.

Presto has a [HiveMetastore](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java) interface that uses its own model objects such as [Table](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/Table.java). Glue implements the interface directly as [GlueMetastore](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java) using the AWS SDK for Java.

Presto also has a [ThriftMetastore](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastore.java) interface that uses the generated libthrift classes such as `org.apache.hadoop.hive.metastore.api.Table` from the Apache Hive dependency (except for table and column statistics classes which don't exist in Hive). The implementation [ThriftHiveMetastore](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java) handles retry and JMX statistics collection, maps Thrift exceptions into Presto exceptions, and some other basic mapping including `null` to `Optional`.

Thrift implements `HiveMetastore` using [BridgingHiveMetastore](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java) which translates to the `ThriftMetastore` interface and converts the model objects using [ThriftMetastoreUtil](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java).

Iceberg needs a smaller number of methods, but the complexity comes from the model objects. Doing a generic conversion from `org.apache.hadoop.hive.metastore.api.Table` to  `com.amazonaws.services.glue.model.Table` seems feasible, since the structures are very similar, but much of the code would go unused (e.g., Iceberg doesn't use Hive partitioning or bucketing). It might be cleaner to duplicate the logic at a higher level using the AWS Glue client directly.

**Comment by vrozov** [comment]
@electrum The PR has 46 files added/modified, and the only relevant to the discussion in this thread class is `io.prestosql.iceberg.HiveTableOperations`, so it was quite easy to miss that file. Anyway, would not it be better to change iceberg `org.apache.iceberg.hive.HiveTableOperations` to allow Presto/Drill/Spark to provide it's own Hive metastore client, instead of re-implementing that class in Presto, especially that `BaseMetastoreTableOperations` that `HiveTableOperations` extends is not part of the iceberg api library?

**Comment by electrum** [comment]
@vrozov I considered that, but the problem is, what would the metastore client API look like? As explained in the previous comment, the Presto `HiveMetastore` interface uses Presto model objects. Trying to write an adapter layer would likely be more complicated and more code than the ~200 lines of the current `HiveTableOperations` class.

More generally, I don't agree that trying to use the same code everywhere is the always the best choice. One of the big advantages of Iceberg is that it's designed to be an open standard with a specification. You need multiple implementations (and compliance tests) to keep the specification honest.

As for `BaseMetastoreTableOperations`, I agree that extending it is problematic (as is subclassing in general). At this point, very little code is used from it, and its design forces some strangeness on the Presto subclass, so it's probably best if the Presto code inlines it.

**Comment by rdblue** [comment]
@electrum, thanks for the explanation. How do you implement the table lock operation for Glue? Is that supported directly in the AWS SDK? If so, we should probably add an iceberg-glue module to support it from Spark.

**Pull request merged**
