### PR TITLE
Refactor AssertHelpers and TestHelpers to Reduce Code Duplication

### LINKED ISSUE #410: Refactor AssertHelpers and TestHelpers
We should refactor `TestHelpers` in iceberg-api and `AssertHelpers` in iceberg-core as they share a lot of code.

### PR DESCRIPTION
**Pull request by sujithjay**
This PR implements and closes #410.

### CODE REVIEW

**Comment by sujithjay** [comment]
Tests fail on CI, they but seem unrelated to the changes. FWIW, the tests pass on my machine. 
```
org.apache.iceberg.spark.source.TestIcebergSourceHiveTables > testHiveFilesUnpartitionedTable FAILED
    java.lang.RuntimeException at TestIcebergSourceHiveTables.java:258
        Caused by: org.apache.thrift.transport.TTransportException at TestIcebergSourceHiveTables.java:258
            Caused by: java.net.SocketException at TestIcebergSourceHiveTables.java:258
```

**Comment by rdblue** [comment]
I restarted the tests. Right now that one is flaky in Travis CI and we're trying to track down why.

**Comment by rdblue** [comment]
Thanks @sujithjay! This looks great. I think we might have more copies of this method elsewhere if you'd like to fix those as well. Thanks!

**Comment by sujithjay** [comment]
Sure, I will try fixing that as well. Thank you.

**Pull request merged**
