### PR TITLE
Remove filter and iterable methods from Snapshot.

### PR DESCRIPTION
**Pull request by rdblue**
These are not used.

### CODE REVIEW

**Comment by rdsr** [comment]
What was the original motivation for adding this?

**Comment by rdblue** [comment]
The original idea was that you would be able to easily list all the files in a Snapshot. That may be a good idea still, but nothing currently uses this. Scan and ManifestGroup read manifests directly for different purposes.

All these may be refactored later because I'm working on a feature branch that moves snapshot manifest listings out of the metadata file to keep it small and make sorting through the files in a table faster (using partition ranges, for example).

**Comment by rdsr** [comment]
That makes sense. Thks!

**Comment by danielcweeks** [comment]
+1

**Pull request merged**
