### PR TITLE
Adding back public access to Builder add method

### PR DESCRIPTION
**Pull request by prodeezy**
Addresses https://github.com/apache/incubator-iceberg/issues/495 to allow setting custom name for transformed partition field.

### CODE REVIEW

**Comment by prodeezy** [comment]
@rdblue  https://github.com/apache/incubator-iceberg/pull/411 took access out for this method. Lemme know if this looks ok to you.

**Comment by rdblue** [comment]
@prodeezy, how are you defining custom transform functions? Does that require adding transforms to Iceberg?

**Comment by rominparekh** [comment]
@rdblue : One example of custom transform usage is to define a custom target column name for an existing transform function. For instance - 
```scala
// gives us `timestamp_day` as target col
PartitionSpec.builderFor(schema)
    .day("timestamp") 

 // gives us `_ADBE_DAY` as target col
PartitionSpec.builderFor(schema)
    .add(1 /* fieldId */, "_ADBE_DAY", "day")
```

cc: @prodeezy

**Comment by rdblue** [comment]
Thanks, @rominparekh. There was more discussion on #495 where @prodeezy gave the same example. I think the right way to make that use case work is to add methods to override the partition field name. Using add allows you to specify the name of the transform, but we don't really want people doing that because it is hard to register transforms.

So instead, let's add something like this:
```java
PartitionSpec.builderFor(schema)
   .day("timestamp", "c_date")
   .build()
```

**Pull request closed without merging**
