### PR TITLE
[BUG] snapshotId() does not reflect the right snapshot id of the snapshot being committed during rollback/cherrypick

### PR DESCRIPTION
**Pull request by rdsr**
The following code highlights the bug. It is not a fix.

### CODE REVIEW

**Comment by rdblue** [comment]
I'm not sure I understand. What behavior are you seeing?

We expect the committed snapshot ID for a cherry-pick to be different, but setting the snapshot ID or rolling back should not create a new snapshot ID.

**Comment by rdsr** [comment]
So when we rollback, I think what happens is that org.apache.iceberg.SnapshotProducer#snapshotId() does not reflect the snapshot id of the snapshot being committed.

In all other cases `SnapshotProducer#apply()` correctly sets the `SnapshotProducer#snapshotId` .  Whereas `SnapshotManager` override `apply()` in which case, `SnapshotProducer#snapshotId` is never initialized.

This was surfaced in #939 when I tried capturing the snapshotId  using the method `SnapshotProducer#snapshotId()` . Since snapshotId is not computed in case of rollback, `SnapshotProducer#snapshotId()` is never initialized to the correct value of the snapshot being committed.

**Comment by rdblue** [comment]
Sounds like we might just need to override `snapshotId` and return the target ID in case of rollback and setting the current snapshot to an existing one?

**Comment by rdsr** [comment]
yea. I'll work on that fix.

**Pull request closed without merging**
