### PR TITLE
Wrap sub-class of PositionAccessor into WrappedPositionAccessor inste…

### PR DESCRIPTION
**Pull request by waterlx**
This PR is to address issue #994

### CODE REVIEW

**Comment by waterlx** [comment]
The most direct way to address #994 is to limit the logic so that only PositionAccessor itself could be wrapped by Position2Accessor. Its sub-classes will be wrapped by WrappedPositionAccessor.

**Comment by rdblue** [comment]
@waterlx, this looks good to me. Can you add a test case?

**Comment by waterlx** [comment]
@rdblue sorry for my late response~~
The PR is updated with a UT added to verify the changes in PartitionKey. Regarding the changes in Accessors, it seems hard to add a UT for it, as PositionAccessor in Accessors does not have any sub-class so far. 
Would you please review it at your most convenience? Thanks!

**Comment by rdblue** [comment]
The test looks good. I fixed the checkstyle error so hopefully tests pass and I can merge this. Thanks, @waterlx!

**Comment by rdblue** [comment]
Since this didn't get picked up by CI, I ran `./gradlew check` locally and everything looks good so I'll merge.

Thanks for fixing this, @waterlx!

**Pull request merged**
