### PR TITLE
Static import the method of Preconditions.checkArgument

### PR DESCRIPTION
**Pull request by leoluan2009**
1. static import the method of Preconditions.checkArgument to reduce code and make code cleaner

2. replace org.apache.parquet.Preconditions.checkArgument to com.google.common.base.Preconditions.checkArgument

3. replace org.apache.arrow.util.Preconditions.checkArgument to com.google.common.base.Preconditions.checkArgument

### CODE REVIEW

**Comment by rdblue** [comment]
Hi @leoluan2009, thanks for contributing. We don't use static imports, so we don't want to merge change 1. But fixing instances where we have accidentally used an alternative `Preconditions` class is really useful. Could you update and remove the static imports?

**Comment by leoluan2009** [comment]
Hi @rdblue , thanks for your review.
Would you please tell me why we don't use static imports, I think good using of static imports can make code cleaner, maybe I am wrong.

**Comment by rdblue** [comment]
Not using static method imports is what most people wanted. It provides additional context at a method call so it is easier to see what's happening. Many methods have the same name, so it's good to know which implementation you're using.

**Comment by rdblue** [comment]
I'm going to close this since there hasn't been an update. Feel free to re-open if you decide to remove the static import changes. Thanks!

**Comment by leoluan2009** [comment]
Sorry for update late, I have send a another PR https://github.com/apache/incubator-iceberg/pull/911 to unify the usage of Preconditions

**Comment by rdblue** [comment]
No problem about the timing, I was just trying to keep the number of PRs manageable. You're always welcome to re-open or re-submit if that happens.

**Pull request closed without merging**
