### PR TITLE
Rename some implementations for consistency

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR renames some classes to be consistent with the rest of the codebase.

### CODE REVIEW

**Comment by rdblue** [comment]
If you don't mind, I'd like to get some of the other PRs that touch these files in first, since this could cause conflicts and it should be easier to run a rename again than to fix conflicts in a bunch of other PRs. Is that okay?

**Comment by aokolnychyi** [comment]
Sounds good to me!

**Comment by rdblue** [comment]
@aokolnychyi, I think the other PRs are in if you want to rebase this one.

**Comment by aokolnychyi** [comment]
@rdblue, rebased

**Comment by aokolnychyi** [comment]
Seems like Python tests fail for everyone

**Pull request merged**
