### PR TITLE
Upgrade Apache ORC to 1.6.3

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to upgrade Apache ORC dependency to 1.6.3 in order to bring the latest bug fixes.

- https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12318320&version=12346545

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you for review and approval, @Fokko .

**Comment by dongjoon-hyun** [comment]
cc @omalley

**Comment by aokolnychyi** [comment]
I feel like me might want to do 0.8.1 with the new ORC and Parquet version (i.e. the jar size problem).

**Comment by rdblue** [comment]
Thanks, @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you for review and merging, @rdblue . Also, thank you, @aokolnychyi , @Fokko .

**Pull request merged**
