### PR TITLE
make fieldIds in SchemaVisitor thread safe

### PR DESCRIPTION
**Pull request by chenjunjiedada**
This fixes https://github.com/apache/incubator-iceberg/issues/831.

### CODE REVIEW

**Comment by rdblue** [comment]
I don't think that the right solution to concurrent access is to use a concurrent queue. That avoids the exception you're seeing, but doesn't mean that the code is correct.

It looks like the problem is that a shared `SchemaVisitor`, in this case `MappingUtil.CreateMapping.INSTANCE`, has multiple threads updating the visitor's internal field ID stack. Since that stack is specific to the schema that is visited, it isn't correct to share the stack across threads. This was an oversight because the actual visitor doesn't keep any state so it seemed safe to share one instead of creating a new one each time.

The solution is to either avoid creating singleton `SchemaVisitor` instances, or to remove the field ID stack. I think we should remove the field ID stack, since it is only used when converting an Iceberg type to Avro (`TypeToSchema`).

**Comment by chenjunjiedada** [comment]
Thanks @rdblue for the explanation.

I walked through the code path and found that we still need the `id` to for the record name since we need to do Avro resolution via name mapping when parsing the `ManifesEntry` and `ManifestFile`, which means we need to build a same name mapping (or with some renames) against the schema we define for `ManifesEntry` and `ManifestFile`.  If we remove the `fieldIds` we need to find another way to do the same schema visiting logic that may be more complicated.  Make sense?

**Comment by rdblue** [comment]
@chenjunjiedada, you're right that we do need the id to produce the record name. That doesn't mean that we need to include the field id stack in _all_ of the schema visitors. A simple solution is to use a different schema visitor for the one case that needs the id.

**Comment by chenjunjiedada** [comment]
Thanks, I got it. Will update this later.

**Comment by rdblue** [comment]
Ideally, this wouldn't create a new visitor for the one case that uses the field IDs. I opened a #840 with an alternative solution that uses new callbacks instead of a different visitor pattern. Could you look at that?

**Comment by chenjunjiedada** [comment]
I tried the way you provided, just have one concern that all other schema visitors are forced to add one more stack frame, not sure if that could be optimized by the compiler.

**Comment by rdblue** [comment]
The solution in #840 won't add more stack frames because the calls are invoked and return outside the recursive call to `visit`.

I merged the other version so I'm going to close this. Thanks @chenjunjiedada!

**Pull request closed without merging**
