### PR TITLE
Optimize ExpressionVisitors.visit method to traverse minimum nodes number required for determining the result

### PR DESCRIPTION
**Pull request by vvysotskyi**
For issue #439

### CODE REVIEW

**Comment by rdblue** [comment]
Thanks for working on this, @vvysotskyi. This looks like a good start, but it isn't safe to update the visitor like this. The visitors may be parameterized by Boolean or Expression or something else. If parameterized by boolean, like an evaluator, then this wouldn't work. And if parameterized by expression, then there is no guarantee that this is going to be correct for the operation that uses the visitor pattern.

I suggest adding a new `visit` method called `visitEvaluator` that accepts `ExpressionVisitor<Boolean>` and applies the short-circuit logic using the boolean returned by the eval visitor.

**Comment by vvysotskyi** [comment]
@rdblue, thanks for code review and your suggestions, I have made requested changes.
I have replaced usage of the existing method `visit()` with the new `visitEvaluator()` method for `Boolean` visitors.

I've also thought about the way, how we can optimize it for `Expression` visitors, since some of them may use `True.INSTANCE` and `False.INSTANCE` expressions. It is possible to add methods which accept suppliers into `ExpressionVisitor` and override these methods with short-circuit logic in some implementations where it will not cause issues, what do you think about this?

**Comment by rdblue** [comment]
Thanks @vvysotskyi! This looks good and is covered by current tests so I'm going to merge it. We can follow up with more short-circuit methods later.

**Comment by rdblue** [comment]
> I've also thought about the way, how we can optimize it for Expression visitors, since some of them may use True.INSTANCE and False.INSTANCE expressions. It is possible to add methods which accept suppliers into ExpressionVisitor and override these methods with short-circuit logic in some implementations where it will not cause issues, what do you think about this?

If there are others that would benefit, I think we should add a new visit method for this that checks for `True.INSTANCE` and `False.INSTANCE`. That can be used for visitors that support short-circuit evaluation.

**Pull request merged**
