### PR TITLE
Initial python implementation

### PR DESCRIPTION
**Pull request by TGooch44**
Initial check-in for iceberg python implementation. This implementation closely follows the java implementation.  It is still under progress, but has a large portion of the api package and associated tests implemented.  Work is underway to start completing the more functional parts of the core package.

### CODE REVIEW

**Comment by mccheah** [comment]
Is there any way we could build this more incrementally? 10,000 lines is a lot of code to review.

**Comment by TGooch44** [comment]
@mccheah It may be difficult to break up because there is a lot of interdependency.  I'll see what I can do to break apart some of the packages.

@xhochy The actual core part of the library is still incomplete, the best place to start looking is in the iceberg.api package.  You can see examples of usage in the tests/api folder.  Let me know if you have any questions and I'm happy to answer, I appreciate you taking a look.

**Comment by rdblue** [comment]
@xhochy, great to see you in the Iceberg community!

I think we could use some help making sure the API looks pythonic. @TGooch44 has done a great job porting the Java library over to Python, including tests for the components so we are fairly confident that what it is doing matches the behavior of Java and is correct. But there are some cases where the code is probably quite odd to pythonistas, like the translation of Java interfaces that throw a RuntimeError instead of allowing dynamic typing to throw NoSuchMethodError. Your opinion on those areas would be appreciated!

**Comment by rdblue** [comment]
Thank you for looking at this @xhochy! I think your suggestions sound reasonable.

**Comment by TGooch44** [comment]
@xhochy I really appreciate all the review, I'll go through these and review, but as Ryan mentioned it all sounds reasonable, so unless I have any questions I'll start implementing everything  you've suggested.

**Comment by feng-tao** [comment]
@rdblue @TGooch44 , will we have a pypi for the iceberg python library?

**Comment by rdblue** [comment]
@feng-tao, we plan to push a convenience copy to pypi for the first release. But we need to make an Apache release before we push anything to pypi.

**Pull request merged**
