### PR TITLE
Support from Python 3.6+

### PR DESCRIPTION
**Pull request by Fokko**
We test against Python 3.6. So it makes sense to support from 3.6 and onwards.

### CODE REVIEW

**Comment by Fokko** [comment]
CI fails because of https://github.com/apache/incubator-iceberg/pull/794

**Comment by rdblue** [comment]
Reopening to trigger Travis. I tried restarting the python test, but it didn't pick up the fix from #794.

**Comment by Fokko** [comment]
Merged master into the branch, it should be green now 🤞

**Comment by rdblue** [comment]
Merged! Thanks @Fokko!

**Pull request merged**
