### PR TITLE
Store split offsets for ORC files

### PR DESCRIPTION
**Pull request by rdsr**
I had to reopen the file with an ORC reader to get the stripe offsets. Stripe information is cached in the writer but it is not made public AFAICT.  If folks are OK with the approach, I will try to add tests for this, similar to #186 

cc: @edgarRd

### CODE REVIEW

**Comment by rdblue** [comment]
Thanks @rdsr! Can you add a test for this like the one for Parquet?

**Comment by rdsr** [comment]
@rdblue I guess you mean this test [TestBasicWrite](https://github.com/samarthjain/incubator-iceberg/blob/007d85c162533601d5d4e8f11286185d8bdda851/spark/src/test/java/org/apache/iceberg/spark/source/TestParquetWrite.java). The problem here is that I cannot simple update that test as Spark write support for ORC is not available. I'll try to write a separate ORC standalone test similar to `TestBasicWrite` but without the Spark engine support. 

Thanks

**Comment by rdblue** [comment]
Good point. Let's at least get some test in that validates we get the splits, but I see what you mean that we can't build an end-to-end test.

**Comment by edgarRd** [comment]
Thanks for adding this @rdsr. I assume that a test within the ORC package should be possible and validating that the splits are correctly retrieved.

**Comment by edgarRd** [comment]
On the other hand, I think this may be a separate question, but do we want write support in ORC at all? Or should we just remove all the code related to writes and just not support it in Iceberg?
I assume for most people the main use case would be to easily migrate existing ORC datasets, but moving forward to write in Parquet.

What do you think?

**Comment by rdsr** [comment]
Hi @edgarRd, my take would be to keep the write support we currently have. Different companies will have different preferences and if folks would like to contribute and improve ORC support, without negatively affecting the Iceberg abstractions/APIs,  we should allow that.  This could help Iceberg get more adoption and contributions.

**Comment by rdblue** [comment]
I agree, there's no need to make that choice for people using Iceberg. If someone wants to use ORC, it should ideally work. But we need to get it to where we can guarantee the same behavior as the other formats.

**Comment by rdblue** [comment]
Thanks for adding a test, @rdsr! I just merged this.

**Pull request merged**
