### PR TITLE
Use "org.apache.iceberg" package name

### LINKED ISSUE #53: Use "org.apache.iceberg" package name

### PR DESCRIPTION
**Pull request by vrozov**
Closes #53

### CODE REVIEW

**Comment by vrozov** [comment]
@rdblue Please review

**Comment by mccheah** [comment]
Conflicts in a lot of places. Think it would be great to take a look at this soon - would like this to unblock code linting work for 1.x too.

**Comment by rdblue** [comment]
Yeah, I haven't looked at this much because I think we will want to plan when we switch over. It will break other pull requests. It's also a fairly simple change in an IDE, so I wouldn't worry about the conflicts. We can just refactor when the time comes.

**Comment by rdblue** [comment]
This was done by #138. I'm going to close this PR.

**Pull request closed without merging**
