### PR TITLE
IcebergGenerics should support ORC format

### PR DESCRIPTION
**Pull request by leoluan2009**
For issue [https://github.com/apache/incubator-iceberg/issues/848](https://github.com/apache/incubator-iceberg/issues/848)
@rdsr  please help to review, thanks

### CODE REVIEW

**Comment by rdsr** [comment]
@leoluan2009 would it make sense to have tests for it.
Iceberg already has a few tests written for IcebergGenerics which work on Parquet and Avro. Maybe all we need to do it enable it for ORC as well?

The class I'm talking about is `org.apache.iceberg.data.TestLocalScan`. It currently supports Avro, and Parquet like so
```
 @Parameterized.Parameters
  public static Object[][] parameters() {
    return new Object[][] {
        new Object[] { "parquet" },
        new Object[] { "avro" }
    };
  }
```

**Comment by leoluan2009** [comment]
@rdsr  Thanks for your review, and I will add some tests later.

**Comment by rdblue** [comment]
Looks good to me, thanks @leoluan2009!

**Comment by leoluan2009** [comment]
Thank you to merge, @rdsr and @rdblue

**Pull request merged**
