### PR TITLE
Replace hidden dependency on commons-compress with JDK zip

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by rdblue** [comment]
+1

@electrum, the validation failure is caused by extra newlines in imports. I'll merge once this is passing checkstyle.

**Comment by electrum** [comment]
Thanks, I need to update my IntelliJ config for this project.

**Comment by electrum** [comment]
@rdblue The build passed. I learned to run `gradle check` locally (install to local Maven repo doesn’t do checks).

**Comment by rdblue** [comment]
Thanks @electrum! Merged.

**Pull request merged**
