### PR TITLE
Move identifier validation into BaseMetastoreCatalog

### PR DESCRIPTION
**Pull request by rdblue**
For catalogs that extend `BaseMetastoreCatalog`, identifier validation is difficult to implement. Identifiers should be validated before they are passed to `newTableOps` because validation in `newTableOps` doesn't have enough information to throw the correct exception: from `createTable` it should throw a `ValidationException` but from `loadTable` it should throw `NoSuchTableException`.

It is also difficult to ensure that metadata tables work with identifier validation because metadata tables rely on a valid identifier but may not be a valid identifier themselves. For example, Hive tables require 1 level of namespacing, but metadata tables use the full valid table identifier as a namespace.

This moves validation to a method that can be overridden and fixes some of these difficult cases and ensures that `newTableOps` is only called for a valid identifier.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
I am wondering if there will be any unexpected consequences for throwing `NoSuchTableException` instead of `ValidationException` or `IllegalArgumentException`. For example, `tableExists` in Iceberg and Spark catalogs is implemented in a way that will swallow the exception and simply report `false`.

**Comment by rdblue** [comment]
> tableExists in Iceberg and Spark catalogs is implemented in a way that will swallow the exception and simply report false

I think that's the expected behavior. That's why I updated this to throw `NoSuchTableException`. Shouldn't `tableExists` always return a boolean and not throw a `ValidationException`? I think users expect `tableExists` to be safe if they pass in an identifier.

**Comment by aokolnychyi** [comment]
I double checked with Spark, seems to be in line with `TableIdentifierHelper`. @rdblue, could you resolve the conflicts so that we can merge it?

**Comment by rdblue** [comment]
Rebased.

**Pull request merged**
