### PR TITLE
Fix typo in the message for refreshing table metadata

### PR DESCRIPTION
**Pull request by waterlx**
@rdblue , I think we need to change from "from new version" to "to new version". Please correct me if I get a wrong understanding here.

### CODE REVIEW

**Comment by jerryshao** [comment]
LGTM, +1

**Comment by rdblue** [comment]
I don't think this is a typo. The metadata is being refreshed from the location shown in the log message and it seems strange to me to use "to" instead. I'd prefer to leave this as is, or maybe update this to "from location" to make it more clear.

**Comment by waterlx** [comment]
Hi @rdblue , I am a little confused. Please help to clarify, thanks!
Regarding the functions of https://github.com/apache/incubator-iceberg/blob/a509e43cf93d223a3925cbdcc5a0df4ac997b889/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L134
1. If newLocation is the source location where the metadata is being refreshed from, could you please share your idea about what `currentMetadataLocation` stands for?
2. Does the message of "Refreshing table metadata from new version: newLocation" indicate that meta data is being refreshed from `newLocation`, not that the mata data is being refreshed from `currentMetadataLocation` to `newLocation` ? Before this message is issued, shown in `SHOW CREATE TABLE` of Hive, `metadata_location` in TBLPROPERTIES is `newLocation`, while `previous_metadata_location` is `currentMetadataLocation`. So does that message mean that the meta data is being refreshing from `newLocation` to somewhere else？

**Comment by rdblue** [comment]
> If newLocation is the source location where the metadata is being refreshed from, could you please share your idea about what currentMetadataLocation stands for?

`TableOperations` keeps track of the location that metadata was last read from. When refreshing, the location from the metastore is passed to `refreshFromMetadataLocation`, which may be the same as the currently loaded one that was used, or it may be new and should replace the currently loaded one.

> Does the message of "Refreshing table metadata from new version: newLocation" indicate that meta data is being refreshed from newLocation, not that the mata data is being refreshed from currentMetadataLocation to newLocation ?

It indicates that `newLocation` is not the currently loaded location, so the metadata will be refreshed from the new location.

I think the confusion is because there are two "current" states. The `TableOperations` instance has a current state that is only updated when `refresh` is called. And the table itself has a current state in the metastore. The `refreshFromMetadataLocation` method is updating the current state of `TableOperations` from the current state fetched from the metastore, the `newLocation`.

**Comment by waterlx** [comment]
Thanks for the detailed explanation! Got your idea!

**Comment by waterlx** [comment]
"Refreshing table metadata from new version: aaa" indicates that Iceberg is refreshing the table metadata maintained in `TableOperations` (so called "currently loaded one", that is, the value of `currentMetadataLocation` in `BaseMetastoreTableOperations`) to use the value fetched from the metastore, that is, `newLocation` in `refreshFromMetadataLocation()`.

"from new location" still cause confusions IMHO, but which is trivial.

**Pull request closed without merging**
