### PR TITLE
Use a shared client in Hive table tests

### PR DESCRIPTION
**Pull request by rdblue**

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@rdblue, do you happen to know why we have test failures only in iceberg-spark even though `TestHiveMetastore` is used in multiple places?

**Comment by rdblue** [comment]
I think this has something to do with the connections created by the Hive hack that gets a connection from Spark. I'm surprised that reusing it doesn't work, but maybe it's accessed from multiple tests and we aren't actually able to reuse the connection?

**Comment by rdblue** [comment]
Okay, once I actually took a good look at those tests it was more obvious. Each test instantiates a new catalog with its own client pool. So it was easy for these to conflict if the tests run in parallel.

I'm pushing a fix that uses a single shared catalog. I'm also keeping the other changes since those clean up client handling a bit.

**Comment by rdblue** [comment]
@aokolnychyi, I think I found the problem. Can you review?

**Pull request merged**
