### PR TITLE
Move BaseTransaction factory methods to Transaction

### PR DESCRIPTION
**Pull request by electrum**
This allows using it outside of BaseMetastoreTables.

### CODE REVIEW

**Comment by rdblue** [comment]
@electrum, can you give more context on where you need to use this? This is probably for create and replace operations in catalogs that aren't defined in Iceberg?

I'd prefer to move the static methods that are made public here to a `Transactions` class instead of making `BaseTransaction` public. I don't think there's a need to expose that class, just the factory methods.

**Comment by electrum** [comment]
I’m using this to create a `Transaction` instance directly, without using `BaseMetastoreTables` (as we have an alternate implementation).

Do you want a new `Transactions` class, or should they be static methods on the `Transaction` interface? The latter seems to be the favored way for Java 8 (it’s why they added static methods for interfaces).

**Comment by rdblue** [comment]
@electrum, we use the plural convention in most places to keep the interfaces cleaner, so I'd say use `Transactions`.

**Comment by electrum** [comment]
@rdblue updated

**Comment by rdblue** [comment]
Merged. Thanks @electrum!

**Pull request merged**
