### PR TITLE
[MINOR] Throw an exception early if there is no dict available instead of handling dictionary-encoded pages for absent dict

### PR DESCRIPTION
**Pull request by fbocse**

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@fbocse this PR still seems relevant, right? Mind rebasing?

**Comment by fbocse** [comment]
@aokolnychyi don't know if relevant tbh but did the rebase regardless, thank you for the heads-up

**Comment by aokolnychyi** [comment]
LGTM. @rdblue what do you think?

**Comment by rdblue** [comment]
Looks good to me. If `dict` returned null, further uses would fail with a null pointer exception. So this should be safe.

**Pull request merged**
