### PR TITLE
Update link url in doc

### PR DESCRIPTION
**Pull request by chenjunjiedada**
api-quickstart.md

### CODE REVIEW

**Comment by rdblue** [comment]
@chenjunjiedada, these links work fine when I test them. What is the purpose of this change?

**Comment by chenjunjiedada** [comment]
@rdblue, It doesn't work on master when I read the doc yesterday.  Could you please have a try again.

**Comment by rdblue** [comment]
@chenjunjiedada, I think I understand the confusion. These links are for the [Apache site](https://iceberg.apache.org). I don't think we can make them work on that site and in github at the same time, unfortunately. Feel free to try it out by running `mkdocs serve` in the site directory.

**Comment by chenjunjiedada** [comment]
I see, thanks for clarification.

**Comment by rdblue** [comment]
Thanks for taking the time to fix this and then to close the issue, @chenjunjiedada! I really appreciate helping us keep docs up to date, even if it didn't get merged.

**Pull request closed without merging**
