### PR TITLE
Remove unused conversions file

### PR DESCRIPTION
**Pull request by feng-tao**
I Just look at the python implementation. It seems this file is committed incorrectly as there is another conversions file in https://github.com/apache/incubator-iceberg/blob/master/python/iceberg/api/types/conversions.py

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @TGooch44 @rdblue

**Comment by rdblue** [comment]
I think this is probably going to be needed as we build out support for min/max stats in the python implementation. @TGooch44, what do you think?

**Comment by feng-tao** [comment]
@rdblue there are two files: one https://github.com/apache/incubator-iceberg/blob/master/python/iceberg/api/types/conversions.py and https://github.com/apache/incubator-iceberg/blob/master/python/iceberg/api/types/%23conversions.py%23 which are identical. The later one is not a valid python file which we try to remove in this pr.

**Comment by rdsr** [comment]
It seems this was a backup file created by an editor We could also probably update our `.gitignore` together with removing this.

**Comment by rdblue** [comment]
@TGooch44, can you take a look at this?

**Comment by TGooch44** [comment]
I'll get this and update.

**Comment by TGooch44** [comment]
I think we should just remove the file for now, and update the .gitignore with some of the compiled python endings. I don't think we need to add editor backup files to the ignore file.

And, then just going forward when there aren't so many files being checked in at once we can just be more diligent about not checking in backup files like that. I've updated my editor to save backups to a different directory to avoid the issue on my side in the future.

**Comment by rdblue** [comment]
Thanks @feng-tao! I merged this.

**Comment by feng-tao** [comment]
thanks @rdblue @TGooch44

**Pull request merged**
